### ISSUE TITLE
RepeatableStack resizes items while loading

### ISSUE THREAD

**Issue by psp589** [muak/AiForms.Layouts#21]
Using RepeatableStack, and load the items one by one, I see an ugly effect, the items gets its width resized every time a new item gets added. How could I prevent this? Am I doing something wrong?
Thank you in advance.

**Comment by psp589** [comment]
I noticed that this happens because the repeatableStack doesn't have enough size for the items once we add a new one, so the items gets resized and after a moment, the repeatableStack grows and the items resize again to its previos size.
For now I have solved it by calculating the size for the repeatable stack before adding the items, but it feels like a hack

**Comment by muak** [comment]
@psp589 

Thank you for your report.

I simply implemented the RepeatableStack without any layout process, so I think it is the cause.
When I have a time, I consider implementing the process of calculating layout size based on your solution.

Alternatively, since the repeatable function, in the future, may be officially implemented in Xamarin.Forms ([https://github.com/xamarin/Xamarin.Forms/pull/4052](https://github.com/xamarin/Xamarin.Forms/pull/4052)), you could wait for it.

Thanks.

**Comment by psp589** [comment]
Great! Thank you :)
